services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: skyplus
      POSTGRES_PASSWORD: skyplus
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - j-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - j-network
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - j-network

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - j-network

  config-server-ms:
    image: cjchika/config-server-ms:latest
    container_name: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - j-network

  service-reg:
    image: cjchika/service-reg:latest
    container_name: service-reg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - j-network

  companyms:
    image: cjchika/companyms:latest
    container_name: company-msc
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8082:8082
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - j-network

  jobms:
    image: cjchika/jobms:latest
    container_name: job-msc
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka
    ports:
      - 8081:8081
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - j-network

  reviewms:
    image: cjchika/reviewms:latest
    container_name: review-msc
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8083:8083
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - j-network

  gatewayms:
    image: cjchika/gatewayms:latest
    container_name: gateway-msc
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8084:8084
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - j-network

networks:
  j-network:
  microservice-network:

volumes:
  postgres_data:
  pgadmin_data:
